version: "3.7"
services:
  authn: # Work on this MFE for development
      image: "docker.io/overhangio/openedx-authn-dev:17.0.0"
      ports:
          - "1999:1999"
      stdin_open: true
      tty: true
      volumes:
          - ../plugins/mfe/apps/mfe/webpack.dev-tutor.config.js:/openedx/app/webpack.dev-tutor.config.js:ro
          - /home/gradmin/frontend-app-authn:/openedx/app
          - /openedx/app/node_modules
      restart: unless-stopped
      environment:
          - "PORT=1999"